GET http://localhost:8080
###

GET http://localhost:8080/dsDienThoai
###

GET http://localhost:8080/dsMatHang
###

GET http://localhost:8080/dsHocSinh
###

GET http://localhost:8080/dsTivi
###

POST http://localhost:8080/Cap_nhat_Tivi

{
    "Ma_so" : "Tivi001",
    "Don_gia_Ban" : 500000
}
###

POST http://localhost:8080/Dangnhap

{
    "user" : "kimthanh",
    "pwd" : 123456
}
###

GET http://localhost:8080/MON_AN_7.png
###

